CREATE TABLE USERS(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  	username VARCHAR(30) UNIQUE NOT NULL,
  	password_hash VARCHAR(100) NOT NULL,
  	access_token VARCHAR(30)
);

CREATE TABLE SESSIONS(
  	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	player1_id INT(6) UNSIGNED NOT NULL,
  	player2_id INT(6) UNSIGNED,
  	turn ENUM('p1', 'p2') NOT NULL DEFAULT 'p1',
  	winner ENUM('p1', 'p2'),
        next_piece INT(6) UNSIGNED,
	FOREIGN KEY (player1_id) REFERENCES USERS(id),
	FOREIGN KEY (player2_id) REFERENCES USERS(id),
        FOREIGN KEY (next_piece) REFERENCES PIECES(id)
);

CREATE TABLE PIECES(
  	id INT(1) UNSIGNED PRIMARY KEY,
	attr1 BOOLEAN NOT NULL,
	attr2 BOOLEAN NOT NULL,
	attr3 BOOLEAN NOT NULL,
	attr4 BOOLEAN NOT NULL
);

CREATE TABLE PLACEMENTS(
  	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	session_id INT(6) UNSIGNED NOT NULL,
	player_id INT(6) UNSIGNED NOT NULL,
	piece_id INT(6) UNSIGNED NOT NULL,
	pos_x INT(1) UNSIGNED NOT NULL CHECK ((pos_x >= 0) and (pos_x <= 3)),
	pos_y INT(1) UNSIGNED NOT NULL CHECK ((pos_y >= 0) and (pos_y <= 3)),
	FOREIGN KEY (player_id) REFERENCES USERS(id),
	FOREIGN KEY (session_id) REFERENCES SESSIONS(id) 
          ON DELETE CASCADE
);


